name: oxygen
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^0.1.3
  cached_network_image: ^2.0.0
  dio: ^3.0.10
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.0
  shared_preferences: ^0.5.12+4
  shimmer: ^1.0.1
  flutter_staggered_animations: ^0.1.2

  flutter_local_notifications: ^1.4.3
  flare_flutter: ^2.0.1
  carousel_slider: ^2.3.1
  fluttertoast: ^4.0.0
  localize_and_translate: ^3.0.2
  tinycolor: ^1.0.2
  pin_code_text_field: ^1.6.0
  flutter_rating_bar: ^3.2.0+1
  flutter_html:

  confirm_dialog: 
  timer_count_down: 
  awesome_bottom_navigation: 
  fancy_bottom_navigation: 
  curved_navigation_bar: 
  kf_drawer:
  flutter_staggered_grid_view: 
  #google_maps_flutter: 

dev_dependencies:
  flutter_test:
    sdk: flutter
    


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/animations/loading.flr
    - assets/langs/
    - assets/langs/ar.json
    - assets/langs/en-gb.json


  fonts:

    - family: JannaLT-Regular
      fonts:
        - asset: assets/fonts/JannaLT-Regular.ttf
    
    - family: JannaLT-Bold
      fonts:
        - asset: assets/fonts/JannaLT-Bold.ttf
  
